package ke.co.suncha.simba.aqua.options;

import ke.co.suncha.simba.admin.helpers.SimbaBaseEntity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Created by maitha on 10/24/16.
 */
@Entity
@Table(name = "system_options")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class SystemOption extends SimbaBaseEntity {
    // ==============
    // PRIVATE FIELDS
    // ==============

    // An autogenerated id
    @Id
    @NotNull
    @Column(name = "option_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long optionId;

    @NotNull
    @Column(name = "option_name", unique = true)
    private String name;

    @Column(name = "option_value")
    private String value;

    @Column(name = "option_description")
    private String description = "Not Available";

    /**
     * @return the optionId
     */
    public long getOptionId() {
        return optionId;
    }

    /**
     * @param optionId the optionId to set
     */
    public void setOptionId(long optionId) {
        this.optionId = optionId;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the value
     */
    public String getValue() {
        return value;
    }

    /**
     * @param value the value to set
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        if (this.description == null) {
            this.description = "Not Available";
        }
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

}
