/*
 * The MIT License
 *
 * Copyright 2015 Maitha Manyala.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ke.co.suncha.simba.admin.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

import ke.co.suncha.simba.admin.helpers.SimbaBaseEntity;

/**
 * System action entity class
 * @author Maitha Manyala <maitha.manyala at gmail.com>
 *
 */
@Entity
@Table(name = "system_actions")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class SystemAction  extends SimbaBaseEntity {
	// ==============
	// PRIVATE FIELDS
	// ==============

	// An autogenerated id (unique for each user in the db)
	@Id
	@NotNull
	@Column(name = "system_action_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long systemActionId;

	@NotNull
	@Column(name = "name", unique = true)
	private String name;

	@Column(name = "description")
	private String description;

	@NotNull
	@Column(name = "is_active")
	private Boolean active=true;

//	@ManyToMany(cascade = CascadeType.ALL,targetEntity = UserRole.class, fetch = FetchType.LAZY)
//	private List<UserRole> userRoles;


	//@ManyToMany(mappedBy="phones")


	/**
	 * @return the systemActionId
	 */
	public long getSystemActionId() {
		return systemActionId;
	}


	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the isActive
	 */
	public Boolean isActive() {
		return active;
	}

	/**
	 * @param active the isActive to set
	 */
	public void setIsActive(Boolean active) {
		this.active = active;
	}
}